const KEY='portal-pareceres-v1';
const HEADER_KEY='parecer-cabecalho-professora-v1';
const CACHE_RESET_KEY='portal-pareceres-cache-reset-v3';
if(!localStorage.getItem(CACHE_RESET_KEY)){localStorage.removeItem(KEY);localStorage.removeItem('parecer-em-andamento-v2');localStorage.setItem(CACHE_RESET_KEY,'1')}
if((localStorage.getItem(KEY)||'').length>1500000){localStorage.removeItem(KEY);localStorage.removeItem('parecer-em-andamento-v2')}
const initial={classes:[{id:1,name:'Jardim II A',stage:'Educação Infantil',shift:'Manhã'}],periods:[{id:1,name:'1º semestre de 2026',start:'01/02/2026',end:'30/06/2026',active:true}],students:[],activities:[],reports:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||initial, filter='all';
data.classes=data.classes||initial.classes;data.periods=data.periods||initial.periods;data.students.forEach(s=>{if(!s.classId)s.classId=data.classes[0]?.id});
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function render(){
 const className=id=>data.classes.find(c=>c.id===id)?.name||'Turma não informada', studentClass=s=>s.className||className(s.classId), studentAge=s=>{if(!s.birthDate)return s.age||'Idade não informada';let birth=new Date(s.birthDate+'T00:00:00'),today=new Date(),age=today.getFullYear()-birth.getFullYear();if(today<new Date(today.getFullYear(),birth.getMonth(),birth.getDate()))age--;return `${age} anos`}, activePeriod=data.periods.find(p=>p.active)||data.periods[0];
 $('.term').textContent=activePeriod?activePeriod.name:'Nenhum período cadastrado';
 $('#studentCount').textContent=data.students.length;$('#activityCount').textContent=data.activities.length;$('#reportCount').textContent=data.reports.filter(r=>r.status==='done').length;$('#studentsTotal').textContent=`${data.students.length} alunos`;
 let reported=new Set(data.reports.map(r=>r.studentId)); $('#pendingList').innerHTML=data.students.filter(s=>!reported.has(s.id)).slice(0,4).map(s=>`<div class="simple-row"><div class="avatar">${s.avatar}</div><div><strong>${esc(s.name)}</strong><p>${studentAge(s)} · ${esc(studentClass(s))}</p></div><button class="text-button" onclick="generateFor(${s.id})">Gerar Documento Pedagógico →</button></div>`).join('')||'<p class="muted">Todos os pareceres da turma já foram iniciados.</p>';
 let q=$('#studentSearch')?.value?.toLowerCase()||''; $('#studentsList').innerHTML=data.students.filter(s=>s.name.toLowerCase().includes(q)).map(s=>{let r=data.reports.find(r=>r.studentId===s.id);return `<article class="student-card"><div class="avatar">${s.avatar}</div><div><strong>${esc(s.name)}</strong><p>${studentAge(s)} · ${esc(studentClass(s))}</p></div><span class="status ${r?.status==='done'?'done':''}">${r?.status==='done'?'Parecer concluído':r?'Em elaboração':'Sem parecer'}</span><button class="secondary" onclick="editStudent('${String(s.id)}')">Editar</button></article>`}).join('');
 $('#classesList').innerHTML=data.classes.map(c=>`<article class="student-card"><span class="stat-icon lilac">♧</span><div><strong>${esc(c.name)}</strong><p>${esc(c.stage)} · ${esc(c.shift)} · ${data.students.filter(s=>s.classId===c.id).length} alunos</p></div></article>`).join('')||'<p class="muted">Nenhuma turma cadastrada.</p>';
 $('#periodsList').innerHTML=data.periods.map(p=>`<article class="student-card"><span class="stat-icon orange">◷</span><div><strong>${esc(p.name)}</strong><p>${esc(p.start)} até ${esc(p.end)}</p></div><span class="status ${p.active?'done':''}">${p.active?'Período ativo':'Encerrado'}</span></article>`).join('')||'<p class="muted">Nenhum período cadastrado.</p>';
 $('#activitiesList').innerHTML=data.activities.map(a=>`<article class="activity-card"><span class="date">${esc(a.date)}</span><h2>${esc(a.title)}</h2><p>${esc(a.note)}</p><span class="tag">${esc(a.area)}</span>${a.photos?.length?`<div class="activity-photos">${a.photos.map(photo=>`<img src="${photo}" alt="Foto da atividade">`).join('')}</div>`:''}</article>`).join(''); $('#emptyActivities').style.display=data.activities.length?'none':'block';
 let reports=data.reports.filter(r=>filter==='all'||r.status===filter);$('#reportsList').innerHTML=reports.map(r=>{let s=data.students.find(s=>s.id===r.studentId),activityCount=(r.activityIds||[]).length,completed='';if(r.status==='done'&&r.deliveredAt){let d=new Date(r.deliveredAt.replace(' ','T'));completed=` · Concluído em ${d.toLocaleDateString('pt-BR')} às ${d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`};let files=r.status==='done'?`<div class="file-links"><a href="#" onclick="downloadReport(${r.id});return false">DOCX</a><a href="#" onclick="downloadPdf(${r.id});return false">PDF</a></div>`:'';return `<div class="report-row"><div class="avatar">${s.avatar}</div><div><h3>${esc(s.name)}</h3><p>1º semestre de 2026 · ${activityCount} ${activityCount===1?'atividade vinculada':'atividades vinculadas'} · ${r.status==='done'?'Entregue':'Em elaboração'}${completed}</p>${files}</div><span class="status ${r.status==='done'?'done':''}">${r.status==='done'?'Entregue':'Rascunho'}</span><div class="actions"><button class="secondary" onclick="editReport(${r.id})">${r.status==='done'?'Ver parecer':'Continuar'}</button></div></div>`}).join('')||'<p class="muted">Nenhum parecer nesta categoria.</p>';
}
function open(content){$('#modalContent').innerHTML=content;$('#modal').showModal()}
function close(){ $('#modal').close() }
function studentForm(){open(`<h2 class="modal-title">Novo aluno</h2><p class="modal-subtitle">Inclua um aluno na turma Jardim II A.</p><div class="form-grid"><div class="field"><label>Nome completo</label><input id="name" required autofocus placeholder="Ex.: Beatriz Souza"></div><div class="field"><label>Idade</label><select id="age"><option>4 anos</option><option selected>5 anos</option><option>6 anos</option></select></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="addStudentSave()">Salvar aluno</button></div>`)}
function addStudentSave(){let name=$('#name').value.trim();if(!name)return $('#name').focus();data.students.push({id:Date.now(),name,age:$('#age').value,avatar:name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()});close();save()}
function activityForm(){open(`<h2 class="modal-title">Registrar atividade</h2><p class="modal-subtitle">Conte o que a turma viveu e o que você observou.</p><div class="form-grid"><div class="field"><label>Título da atividade</label><input id="activityTitle" required autofocus placeholder="Ex.: Exploração do jardim"></div><div class="field"><label>Campo de experiência</label><select id="activityArea"><option>O eu, o outro e o nós</option><option>Corpo, gestos e movimentos</option><option>Traços, sons, cores e formas</option><option>Escuta, fala, pensamento e imaginação</option><option>Espaços, tempos, quantidades, relações e transformações</option></select></div><div class="field"><label>Observações da professora</label><textarea id="activityNote" rows="4" placeholder="O que os alunos fizeram, disseram ou descobriram?"></textarea></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="addActivitySave()">Registrar atividade</button></div>`)}
function addActivitySave(){let title=$('#activityTitle').value.trim();if(!title)return $('#activityTitle').focus();data.activities.unshift({id:Date.now(),title,area:$('#activityArea').value,note:$('#activityNote').value.trim()||'Registro de vivência da turma.',date:new Date().toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})});close();save()}
function generator(){if(!data.students.length)return;let options=data.students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');open(`<h2 class="modal-title">Gerar parecer com IA</h2><p class="modal-subtitle">A IA organizará um rascunho com base nas ${data.activities.length} atividades registradas. Seu olhar pedagógico sempre tem a palavra final.</p><div class="form-grid"><div class="field"><label>Aluno</label><select id="reportStudent">${options}</select></div><div class="field"><label>Tom do texto</label><select id="tone"><option>Acolhedor e descritivo</option><option>Objetivo e institucional</option><option>Afetivo e celebrativo</option></select></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="createDraft()">✦ Gerar rascunho</button></div>`)}
function textFor(s){let acts=data.activities.slice(0,3);let intro=`Durante o primeiro semestre, ${s.name.split(' ')[0]} participou com interesse das experiências propostas para a turma.`;if(!acts.length)return `${intro} Em suas interações cotidianas, vem construindo vínculos, ampliando sua autonomia e expressando suas ideias de diferentes maneiras. Seguiremos oferecendo tempos e espaços de escuta, brincadeira e descoberta para acompanhar seu percurso.`;let details=acts.map(a=>`na atividade “${a.title}”, ${a.note.toLowerCase().replace(/\.$/,'')}`).join('; ');return `${intro} Nos registros do período, observamos que ${details}. Essas vivências favoreceram sua curiosidade, expressão e participação no coletivo. ${s.name.split(' ')[0]} segue em processo de desenvolvimento, com importantes conquistas que serão acolhidas e acompanhadas no próximo semestre.`}
function createDraft(){let id=+$(' #reportStudent'.trim()).value,s=data.students.find(s=>s.id===id),old=data.reports.find(r=>r.studentId===id);if(old){close();return editReport(old.id)};let report={id:Date.now(),studentId:id,status:'draft',text:textFor(s)};data.reports.unshift(report);close();save();editReport(report.id)}
function generateFor(id){let s=data.students.find(s=>s.id===id),old=data.reports.find(r=>r.studentId===id);if(old)return editReport(old.id);data.reports.unshift({id:Date.now(),studentId:id,status:'draft',text:textFor(s)});save();editReport(data.reports[0].id)}
function editReport(id){let r=data.reports.find(r=>r.id===id),s=data.students.find(s=>s.id===r.studentId);open(`<h2 class="modal-title">Parecer de ${esc(s.name)}</h2><p class="modal-subtitle">Revise e ajuste o texto antes de concluir.</p><div class="field"><label>Parecer pedagógico</label><textarea id="reportText" rows="12">${esc(r.text)}</textarea></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Fechar</button><button class="secondary" type="button" onclick="saveReport(${id},'draft')">Salvar rascunho</button><button class="primary" type="button" onclick="saveReport(${id},'done')">Concluir parecer</button></div>`)}
function saveReport(id,status){let r=data.reports.find(r=>r.id===id);r.text=$('#reportText').value;r.activityIds=[...document.querySelectorAll('.report-activity:checked')].map(input=>+input.value);r.status=status;close();save();if(status==='done')downloadReport(id)}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{let target=$('#'+b.dataset.view);if(!target)return;document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));target.classList.add('active');$('#headerTitle').textContent=b.textContent.trim();window.scrollTo(0,0)});
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(`.nav-item[data-view="${b.dataset.go}"]`).click());$('#addStudent').onclick=studentForm;$('#addActivity').onclick=activityForm;$('#emptyAddActivity').onclick=activityForm;$('#openGenerator').onclick=generator;$('#studentSearch').oninput=render;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));b.classList.add('active');render()});$('#menuButton').onclick=()=>$('.sidebar').classList.toggle('open');render();

function studentFormV2(){let classes=data.classes.map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.shift)}</option>`).join('');open(`<h2 class="modal-title">Novo aluno</h2><p class="modal-subtitle">Inclua um aluno e vincule-a a uma turma já cadastrada.</p><div class="form-grid"><div class="field"><label>Nome completo</label><input id="name" required autofocus placeholder="Ex.: Beatriz Souza"></div><div class="field"><label>Idade</label><select id="age"><option>4 anos</option><option selected>5 anos</option><option>6 anos</option></select></div><div class="field"><label>Turma</label><select id="studentClass">${classes}</select></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="addStudentSaveV2()">Salvar aluno</button></div>`) }
function addStudentSaveV2(){let name=$('#name').value.trim();if(!name)return $('#name').focus();data.students.push({id:Date.now(),name,age:$('#age').value,classId:+$('#studentClass').value,avatar:name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()});close();save()}
function classForm(){open(`<h2 class="modal-title">Nova turma</h2><p class="modal-subtitle">Cadastre uma turma para disponibilizá-la no cadastro dos alunos.</p><div class="form-grid"><div class="field"><label>Nome da turma</label><input id="className" required autofocus placeholder="Ex.: Jardim I B"></div><div class="field"><label>Etapa</label><select id="classStage"><option>Educação Infantil</option><option>Creche</option><option>Pré-escola</option></select></div><div class="field"><label>Turno</label><select id="classShift"><option>Manhã</option><option>Tarde</option><option>Integral</option></select></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="addClassSave()">Salvar turma</button></div>`) }
function addClassSave(){let name=$('#className').value.trim();if(!name)return $('#className').focus();data.classes.push({id:Date.now(),name,stage:$('#classStage').value,shift:$('#classShift').value});close();save()}
function periodForm(){open(`<h2 class="modal-title">Novo período avaliativo</h2><p class="modal-subtitle">Este período poderá ser usado para organizar os pareceres da rede.</p><div class="form-grid"><div class="field"><label>Nome do período</label><input id="periodName" required autofocus placeholder="Ex.: 2º semestre de 2026"></div><div class="field"><label>Data de início</label><input id="periodStart" type="date"></div><div class="field"><label>Data de término</label><input id="periodEnd" type="date"></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="addPeriodSave()">Salvar período</button></div>`) }
function addPeriodSave(){let name=$('#periodName').value.trim();if(!name)return $('#periodName').focus();data.periods.forEach(p=>p.active=false);data.periods.push({id:Date.now(),name,start:$('#periodStart').value.split('-').reverse().join('/')||'Data não informada',end:$('#periodEnd').value.split('-').reverse().join('/')||'Data não informada',active:true});close();save()}
$('#addStudent').onclick=studentFormV2;$('#addClass').onclick=classForm;$('#addPeriod').onclick=periodForm;

let activityFiles=[];
function activityFormV2(){activityFiles=[];open(`<h2 class="modal-title">Registrar atividade</h2><p class="modal-subtitle">Conte o que a turma viveu e registre até três fotos da atividade.</p><div class="form-grid"><div class="field"><label>Título da atividade</label><input id="activityTitle" required autofocus placeholder="Ex.: Exploração do jardim"></div><div class="field"><label>Campo de experiência</label><select id="activityArea"><option>O eu, o outro e o nós</option><option>Corpo, gestos e movimentos</option><option>Traços, sons, cores e formas</option><option>Escuta, fala, pensamento e imaginação</option><option>Espaços, tempos, quantidades, relações e transformações</option></select></div><div class="field"><label>Observações da professora</label><textarea id="activityNote" rows="4" placeholder="O que os alunos fizeram, disseram ou descobriram?"></textarea></div><div class="field"><label>Fotos da atividade <span class="muted">(até 3 imagens)</span></label><input id="activityPhotos" type="file" accept="image/*" multiple onchange="selectActivityPhotos(this)"><div id="imagePreviews" class="image-previews"></div></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="addActivitySaveV2()">Registrar atividade</button></div>`) }
async function selectActivityPhotos(input){try{let result=await window.PortalImageEditors.processFiles(input.files,3);activityFiles=result.photos;window.currentImageEditorMode=result.mode;$('#imagePreviews').innerHTML=activityFiles.map(src=>`<img src="${src}" alt="Prévia da foto">`).join('')}catch(error){alert(error.message);input.value='';activityFiles=[];$('#imagePreviews').innerHTML=''}}
function addActivitySaveV2(){let title=$('#activityTitle').value.trim();if(!title)return $('#activityTitle').focus();Promise.all(activityFiles.map(file=>new Promise(resolve=>{let reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)}))).then(photos=>{data.activities.unshift({id:Date.now(),title,area:$('#activityArea').value,note:$('#activityNote').value.trim()||'Registro de vivência da turma.',photos,date:new Date().toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})});close();save()})}
function generatorV2(){if(!data.students.length)return;let options=data.students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');open(`<h2 class="modal-title">Novo parecer</h2><p class="modal-subtitle">Escolha o aluno para iniciar um parecer em branco.</p><div class="form-grid"><div class="field"><label>Aluno</label><select id="reportStudent">${options}</select></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="createBlankDraft()">Criar parecer</button></div>`) }
function createBlankDraft(){let id=+$('#reportStudent').value,old=data.reports.find(r=>r.studentId===id);if(old){close();return editReport(old.id)};let report={id:Date.now(),studentId:id,status:'draft',text:'',activityIds:[]};data.reports.unshift(report);close();save();editReport(report.id)}
function generateFor(id){let old=data.reports.find(r=>r.studentId===id);if(old)return editReport(old.id);data.reports.unshift({id:Date.now(),studentId:id,status:'draft',text:'',activityIds:[]});save();editReport(data.reports[0].id)}
function editReport(id){let r=data.reports.find(r=>r.id===id),s=data.students.find(s=>s.id===r.studentId);r.activityIds=r.activityIds||[];let activities=data.activities.map(a=>`<label class="linked-activity"><input class="report-activity" type="checkbox" value="${a.id}" ${r.activityIds.includes(a.id)?'checked':''}><span><strong>${esc(a.title)}</strong><small>${esc(a.date)} · ${esc(a.area)}</small></span>${a.photos?.[0]?`<img src="${a.photos[0]}" alt="Foto da atividade">`:''}</label>`).join('')||'<p class="muted">Cadastre uma atividade antes de vinculá-la ao parecer.</p>';open(`<h2 class="modal-title">Parecer de ${esc(s.name)}</h2><p class="modal-subtitle">Selecione as atividades que fundamentam este parecer e escreva com seu olhar pedagógico.</p><div class="field"><label>Atividades vinculadas ao parecer</label><div class="linked-activities">${activities}</div></div><div class="field"><label>Parecer pedagógico</label><textarea id="reportText" rows="10" placeholder="Escreva aqui as observações sobre o percurso do aluno...">${esc(r.text)}</textarea><button class="ai-adjust" type="button" onclick="adjustTextWithAI()">✦ Ajustar texto com IA</button></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Fechar</button><button class="secondary" type="button" onclick="saveReport(${id},'draft')">Salvar rascunho</button><button class="primary" type="button" onclick="saveReport(${id},'done')">Concluir parecer</button></div>`) }
function adjustTextWithAI(){let field=$('#reportText'),text=field.value.trim();if(!text){field.focus();return}let adjusted=text.replace(/\s+/g,' ').replace(/\s*([,.!?;:])\s*/g,'$1 ').trim();adjusted=adjusted.charAt(0).toUpperCase()+adjusted.slice(1);if(!/[.!?]$/.test(adjusted))adjusted+='.';field.value=adjusted}
$('#addActivity').onclick=activityFormV2;$('#emptyAddActivity').onclick=activityFormV2;$('#openGenerator').onclick=generatorV2;

async function loadActivities(){try{let response=await fetch('api.php?resource=activities');if(!response.ok)throw new Error('Não foi possível carregar as atividades.');data.activities=await response.json();render()}catch(error){console.error(error)}}
async function loadClasses(){try{let response=await fetch('api.php?resource=classes');if(!response.ok)throw new Error('Não foi possível carregar as turmas.');data.classes=await response.json();render()}catch(error){console.error(error)}}
async function addActivitySaveV2(){let title=$('#activityTitle').value.trim();if(!title)return $('#activityTitle').focus();let photos=activityFiles.map(item=>String(item));let activePeriod=data.periods.find(p=>p.active)||data.periods[0];try{let response=await fetch('api.php?resource=activities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,area:$('#activityArea').value,note:$('#activityNote').value.trim()||'Registro de vivência da turma.',photos,classId:1,periodId:activePeriod?.id||1,imageEditorMode:photos.length?window.currentImageEditorMode||'none':'none'})});let result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível salvar a atividade.');close();await loadActivities()}catch(error){alert(error.message)}}
loadActivities();
loadClasses();

function studentFormV3(){open(`<h2 class="modal-title">Novo aluno</h2><p class="modal-subtitle">Inclua os dados do aluno e selecione a turma.</p><div class="form-grid"><div class="field"><label>Nome completo</label><input id="name" required autofocus placeholder="Ex.: Beatriz Souza"></div><div class="field"><label>Data de nascimento</label><input id="birthDate" type="date" required></div><div class="field"><label>Turma</label><select id="studentClass" required><option value="Maternal Único">Maternal Único</option><option value="Maternal Manhã">Maternal Manhã</option><option value="Maternal Tarde">Maternal Tarde</option></select></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="addStudentSaveV3()">Salvar aluno</button></div>`) }
function addStudentSaveV3(){let name=$('#name').value.trim(),birthDate=$('#birthDate').value;if(!name)return $('#name').focus();if(!birthDate)return $('#birthDate').focus();data.students.push({id:Date.now(),name,birthDate,className:$('#studentClass').value,avatar:name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()});close();save()}
$('#addStudent').onclick=studentFormV3;

function studentFormV4(){let options=data.classes.map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.shift)}</option>`).join('');open(`<h2 class="modal-title">Novo aluno</h2><p class="modal-subtitle">Inclua os dados do aluno e selecione a turma cadastrada.</p><div class="form-grid"><div class="field"><label>Nome completo</label><input id="name" required autofocus placeholder="Ex.: Beatriz Souza"></div><div class="field"><label>Data de nascimento</label><input id="birthDate" type="date" required></div><div class="field"><label>Turma</label><select id="studentClass" required>${options}</select></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="addStudentSaveV4()">Salvar aluno</button></div>`) }
function addStudentSaveV4(){let name=$('#name').value.trim(),birthDate=$('#birthDate').value;if(!name)return $('#name').focus();if(!birthDate)return $('#birthDate').focus();data.students.push({id:Date.now(),name,birthDate,classId:+$('#studentClass').value,avatar:name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()});close();save()}
$('#addStudent').onclick=studentFormV4;

function downloadReport(id){let report=data.reports.find(r=>r.id===id),student=data.students.find(s=>s.id===report.studentId),period=data.periods.find(p=>p.active)||data.periods[0],className=student.className||data.classes.find(c=>c.id===student.classId)?.name||'Turma não informada',header=JSON.parse(localStorage.getItem(HEADER_KEY)||'{}');let form=document.createElement('form');form.method='post';form.action='download_parecer.php';form.target='_blank';let fields={name:student.name,birthDate:student.birthDate||'',className,period:period?.name||'Período avaliativo',text:report.text,studentPhoto:student.photo||'',entries:JSON.stringify(report.entries||[]),headerNetwork:header.network||'',headerSchool:header.school||'',headerContact:header.contact||'',headerLogo:header.logo||''};Object.entries(fields).forEach(([name,value])=>{let input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.appendChild(input)});document.body.appendChild(form);form.submit();form.remove()}

let wizard={};
function wizardOpen(html){$('#modal').classList.add('wizard');open(html)}
function wizardClose(){$('#modal').classList.remove('wizard');close()}
function generatorV4(){let options=data.students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');wizard={};wizardOpen(`<p class="wizard-step">ETAPA 1 DE 3 · TEXTO PRINCIPAL</p><h2 class="modal-title">Novo parecer pedagógico</h2><p class="modal-subtitle">Registre as observações mais importantes sobre o percurso do aluno.</p><div class="form-grid"><div class="field"><label>Aluno</label><select id="wizardStudent">${options}</select></div><div class="field"><label>Informações principais do parecer</label><textarea id="wizardText" placeholder="Descreva conquistas, interações, interesses, autonomia e aspectos que merecem acompanhamento..."></textarea><button class="ai-adjust" type="button" onclick="adjustTextWithAI()">✦ Ajustar texto com IA</button></div></div><div class="form-actions"><button class="secondary" type="button" onclick="wizardClose()">Voltar</button><button class="primary" type="button" onclick="wizardActivities()">Próximo</button></div>`)}
function wizardActivities(){let text=$('#wizardText').value.trim();if(!text){$('#wizardText').focus();return}wizard={studentId:+$('#wizardStudent').value,text,activityIds:[],photos:[]};let activities=data.activities.map(a=>`<label class="linked-activity"><input class="wizard-activity" type="checkbox" value="${a.id}"><span><strong>${esc(a.title)}</strong><small>${esc(a.date)} · ${esc(a.area)}</small></span>${a.photos?.[0]?`<img src="${a.photos[0]}" alt="Foto">`:''}</label>`).join('')||'<p class="muted">Nenhuma atividade cadastrada. Você pode continuar e vincular depois.</p>';wizardOpen(`<p class="wizard-step">ETAPA 2 DE 3 · ATIVIDADES E FOTOS</p><h2 class="modal-title">Vivências realizadas</h2><p class="modal-subtitle">Selecione as atividades que fundamentam o parecer e anexe até três imagens complementares.</p><div class="field"><label>Atividades vinculadas</label><div class="linked-activities">${activities}</div></div><div class="field"><label>Fotos complementares <span class="muted">(até 3 imagens)</span></label><input id="wizardPhotos" type="file" accept="image/*" multiple onchange="wizardPhotoCheck(this)"><div id="wizardPreviews" class="image-previews"></div></div><div class="form-actions"><button class="secondary" type="button" onclick="generatorV4()">Voltar</button><button class="primary" type="button" onclick="wizardReview()">Próximo</button></div>`)}
function wizardPhotoCheck(input){let files=[...input.files];if(files.length>3){alert('Adicione no máximo 3 imagens.');input.value='';return}wizard.photos=files;$('#wizardPreviews').innerHTML=files.map(f=>`<img src="${URL.createObjectURL(f)}" alt="Prévia">`).join('')}
function wizardReview(){wizard.activityIds=[...document.querySelectorAll('.wizard-activity:checked')].map(x=>+x.value);let student=data.students.find(s=>s.id===wizard.studentId),acts=data.activities.filter(a=>wizard.activityIds.includes(a.id));wizardOpen(`<p class="wizard-step">ETAPA 3 DE 3 · REVISÃO</p><h2 class="modal-title">Revise o rascunho</h2><p class="modal-subtitle">Nada será entregue ainda. Salve como rascunho ou avance para a prévia final.</p><div class="review-box"><strong>${esc(student.name)}</strong> · ${acts.length} atividade(s) vinculada(s)<br><br>${esc(wizard.text)}</div><div class="form-actions"><button class="secondary" type="button" onclick="saveWizardDraft()">Salvar rascunho</button><button class="secondary" type="button" onclick="wizardClose()">Fechar</button><button class="primary" type="button" onclick="wizardFinalize()">Finalizar parecer</button></div>`)}
function wizardReport(){let found=data.reports.find(r=>r.studentId===wizard.studentId);if(found){found.text=wizard.text;found.activityIds=wizard.activityIds;return found}let r={id:Date.now(),studentId:wizard.studentId,text:wizard.text,activityIds:wizard.activityIds,status:'draft'};data.reports.unshift(r);return r}
function saveWizardDraft(){wizardReport().status='draft';wizardClose();save()}
function wizardFinalize(){let r=wizardReport();r.status='review';save();let s=data.students.find(x=>x.id===r.studentId);wizardOpen(`<p class="wizard-step">PRÉVIA DO PARECER</p><h2 class="modal-title">Confira antes de entregar</h2><p class="modal-subtitle">Este parecer permanece em rascunho até você confirmar a entrega.</p><div class="review-box"><strong>${esc(s.name)}</strong><br><br>${esc(r.text)}</div><div class="form-actions"><button class="secondary" type="button" onclick="wizardClose()">Fechar</button><button class="primary" type="button" onclick="deliverReport(${r.id})">Entregar parecer</button></div>`)}
function deliverReport(id){let r=data.reports.find(x=>x.id===id);r.status='done';r.deliveredAt=new Date().toISOString();clearWizard();wizardClose();save();downloadReport(id);setTimeout(()=>downloadPdf(id),400)}
function downloadPdf(id){let r=data.reports.find(x=>x.id===id),s=data.students.find(x=>String(x.id)===String(r.studentId));let form=document.createElement('form');form.method='post';form.action='download_pdf.php';form.target='_blank';[['name',s.name],['text',r.text]].forEach(([name,value])=>{let input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.appendChild(input)});document.body.appendChild(form);form.submit();form.remove()}
$('#openGenerator').onclick=generatorV4;

const WIZARD_KEY='parecer-em-andamento-v2';
function persistWizard(){localStorage.setItem(WIZARD_KEY,JSON.stringify(wizard))}
function clearWizard(){localStorage.removeItem(WIZARD_KEY)}
function wizardStart(newRegistration=false,draft=null){let options=data.students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');if(newRegistration){clearWizard();wizard={}}else if(draft){wizard=draft}else{let saved=JSON.parse(localStorage.getItem(WIZARD_KEY)||'null');wizard=saved||{}}wizardOpen(`<p class="wizard-step">ETAPA 1 DE 3 · TEXTO PRINCIPAL</p><h2 class="modal-title">Novo parecer pedagógico</h2><p class="modal-subtitle">Registre as observações mais importantes. O rascunho é salvo automaticamente neste dispositivo.</p><div class="form-grid"><div class="field"><label>Aluno</label><select id="wizardStudent" onchange="bufferStepOne()">${options}</select></div><div class="field"><label>Informações principais do parecer</label><textarea id="wizardText" oninput="bufferStepOne()" placeholder="Descreva conquistas, interações, interesses, autonomia e aspectos que merecem acompanhamento...">${esc(wizard.text||'')}</textarea><button class="ai-adjust" type="button" onclick="adjustTextWithAI();bufferStepOne()">✦ Ajustar texto com IA</button></div></div><div class="form-actions"><button class="secondary" type="button" onclick="wizardClose()">Voltar</button><button class="secondary" type="button" onclick="saveInitialDraft()">Salvar rascunho</button><button class="primary" type="button" onclick="wizardActivitiesV2()">Próximo</button></div>`);if(wizard.studentId)$('#wizardStudent').value=wizard.studentId}
function bufferStepOne(){let student=$('#wizardStudent'),text=$('#wizardText');if(student)wizard.studentId=student.value;if(text)wizard.text=text.value;persistWizard()}
function wizardActivitiesV2(){if($('#wizardText'))bufferStepOne();if(!wizard.text?.trim())return wizardStart();let activities=data.activities.map(a=>`<label class="linked-activity"><input class="wizard-activity" type="checkbox" value="${a.id}" ${(wizard.activityIds||[]).includes(a.id)?'checked':''}><span><strong>${esc(a.title)}</strong><small>${esc(a.date)} · ${esc(a.area)}</small></span>${a.photos?.[0]?`<img src="${a.photos[0]}" alt="Foto">`:''}</label>`).join('')||'<p class="muted">Nenhuma atividade cadastrada.</p>';let previews=(wizard.photos||[]).map(src=>`<img src="${src}" alt="Prévia">`).join('');wizardOpen(`<p class="wizard-step">ETAPA 2 DE 3 · ATIVIDADES E FOTOS</p><h2 class="modal-title">Vivências realizadas</h2><p class="modal-subtitle">Selecione atividades já cadastradas ou adicione uma nova vivência.</p><div class="field"><label>Atividades cadastradas</label><div class="linked-activities">${activities}</div><button class="ai-adjust" type="button" onclick="useRegisteredActivities()">+ Usar atividades selecionadas no parecer</button></div><div class="field"><label>Fotos da atividade <span class="muted">(até 3 imagens)</span></label><label id="wizardDropzone" class="dropzone" ondragover="wizardDrag(event)" ondragleave="wizardLeave()" ondrop="wizardDrop(event)"><strong>Arraste as imagens aqui</strong><span>ou clique para escolher arquivos</span><input id="wizardPhotos" type="file" accept="image/*" multiple onchange="wizardPhotoCheck(this)"></label><div id="wizardPreviews" class="image-previews">${previews}</div></div><div class="field"><label>Informações sobre a brincadeira ou as fotos</label><textarea id="wizardPhotoNote" rows="4" oninput="bufferStepTwo()" placeholder="Descreva o que aconteceu, o que o aluno explorou ou demonstrou nas imagens...">${esc(wizard.photoNote||'')}</textarea></div><div class="form-actions"><button class="secondary" type="button" onclick="wizardStart()">Voltar</button><button class="secondary" type="button" onclick="saveDraftEverywhere()">Salvar rascunho</button><button class="primary" type="button" onclick="wizardReviewV2()">Próximo</button></div>`)}
function wizardDrag(e){e.preventDefault();$('#wizardDropzone').classList.add('drag')};function wizardLeave(){$('#wizardDropzone').classList.remove('drag')};function wizardDrop(e){e.preventDefault();wizardLeave();let input=$('#wizardPhotos');input.files=e.dataTransfer.files;wizardPhotoCheck(input)}
function bufferStepTwo(){let note=$('#wizardPhotoNote');let activities=document.querySelectorAll('.wizard-activity');if(activities.length)wizard.activityIds=[...document.querySelectorAll('.wizard-activity:checked')].map(x=>+x.value);if(note)wizard.photoNote=note.value;persistWizard()}
function wizardReviewV2(){bufferStepTwo();let s=data.students.find(x=>x.id===wizard.studentId),acts=data.activities.filter(a=>(wizard.activityIds||[]).includes(a.id));wizardOpen(`<p class="wizard-step">ETAPA 3 DE 3 · REVISÃO</p><h2 class="modal-title">Revise o rascunho</h2><div class="review-box"><strong>${esc(s.name)}</strong> · ${acts.length} atividade(s) vinculada(s)<br><br>${esc(wizard.text)}${wizard.photoNote?`<br><br><strong>Vivências registradas:</strong><br>${esc(wizard.photoNote)}`:''}</div><div class="form-actions"><button class="secondary" type="button" onclick="wizardActivitiesV2()">Adicionar mais</button><button class="secondary" type="button" onclick="saveWizardDraft()">Salvar rascunho</button><button class="primary" type="button" onclick="wizardFinalizeV2()">Finalizar parecer</button></div>`)}
function wizardFinalizeV2(){bufferStepTwo();let report=wizardReport();report.status='review';report.photoNote=wizard.photoNote||'';save();let student=data.students.find(x=>x.id===report.studentId);wizardOpen(`<p class="wizard-step">PRÉVIA FINAL</p><h2 class="modal-title">Parecer pronto para entrega</h2><p class="modal-subtitle">Confira o conteúdo. Ele continua como rascunho até a confirmação abaixo.</p><div class="review-box"><strong>${esc(student.name)}</strong><br><br>${esc(report.text)}${report.photoNote?`<br><br><strong>Vivências registradas:</strong><br>${esc(report.photoNote)}`:''}</div><div class="form-actions"><button class="secondary" type="button" onclick="wizardReviewV2()">Voltar para edição</button><button class="primary" type="button" onclick="deliverReport(${report.id})">Entregar parecer</button></div>`)}
$('#openGenerator').onclick=()=>wizardStart(true);

function fileAsDataUrl(file){return new Promise((resolve,reject)=>{let reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
async function wizardPhotoCheck(input){try{let result=await window.PortalImageEditors.processFiles(input.files,3);wizard.photos=result.photos;wizard.imageEditorMode=result.mode;persistWizard();$('#wizardPreviews').innerHTML=wizard.photos.map(src=>`<img src="${src}" alt="Prévia">`).join('')}catch(error){alert(error.message||'Não foi possível ler uma das imagens.');input.value=''}}
function wizardReport(){let found=data.reports.find(r=>r.studentId===wizard.studentId);let payload={text:wizard.text,activityIds:wizard.activityIds||[],photoNote:wizard.photoNote||'',photos:wizard.photos||[]};if(found){Object.assign(found,payload);return found}let report={id:Date.now(),studentId:wizard.studentId,status:'draft',...payload};data.reports.unshift(report);return report}
function editReport(id){let report=data.reports.find(r=>r.id===id);if(!report)return;let draft={studentId:report.studentId,text:report.text||'',activityIds:[],photoNote:'',photos:[],entries:report.entries||[{activityIds:report.activityIds||[],photoNote:report.photoNote||'',photos:report.photos||[]}]};wizard=draft;persistWizard();wizardStart(false,draft)}

function wizardEntries(){return [...(wizard.entries||[]),{activityIds:wizard.activityIds||[],photoNote:wizard.photoNote||'',photos:wizard.photos||[]}].map(item=>({...item,activityIds:item.activityIds||[],photos:item.photos||[],photoNote:item.photoNote||''})).filter(item=>item.activityIds.length||item.photoNote||item.photos.length)}
function wizardAddMore(){bufferStepTwo();let current={activityIds:wizard.activityIds||[],photoNote:wizard.photoNote||'',photos:wizard.photos||[]};if(current.activityIds.length||current.photoNote||current.photos.length){wizard.entries=[...(wizard.entries||[]),current]};wizard.activityIds=[];wizard.photoNote='';wizard.photos=[];persistWizard();wizardActivitiesV2()}
function importSelectedRegisteredActivities(){let selected=(wizard.activityIds||[]).map(String);let existing=new Set((wizard.entries||[]).flatMap(entry=>(entry.activityIds||[]).map(String)));let additions=data.activities.filter(activity=>selected.includes(String(activity.id))&&!existing.has(String(activity.id))).map(activity=>({activityIds:[activity.id],photoNote:activity.note||activity.title,photos:activity.photos||[]}));if(additions.length)wizard.entries=[...(wizard.entries||[]),...additions];wizard.activityIds=[];return additions.length}
function useRegisteredActivities(){bufferStepTwo();let count=importSelectedRegisteredActivities();if(!count)return alert('Selecione uma atividade ainda não adicionada.');persistWizard();alert(`${count} atividade(s) adicionada(s) ao parecer.`);wizardReviewV2()}
function wizardReviewV2(){bufferStepTwo();let s=data.students.find(x=>x.id===wizard.studentId),entries=wizardEntries(),activityTotal=entries.reduce((sum,item)=>sum+item.activityIds.length,0),images=entries.flatMap(item=>item.photos).map(src=>`<img src="${src}" alt="Foto da atividade">`).join('');wizardOpen(`<p class="wizard-step">ETAPA 3 DE 3 · REVISÃO</p><h2 class="modal-title">Revise o rascunho</h2><div class="review-box"><strong>${esc(s.name)}</strong> · ${activityTotal} atividade(s) vinculada(s)<br><br>${esc(wizard.text)}${entries.map(item=>item.photoNote?`<br><br><strong>Vivências registradas:</strong><br>${esc(item.photoNote)}`:'').join('')}</div>${images?`<div class="activity-photos">${images}</div>`:''}<div class="form-actions"><button class="secondary" type="button" onclick="wizardAddMore()">Adicionar mais</button><button class="secondary" type="button" onclick="saveWizardDraft()">Salvar rascunho</button><button class="primary" type="button" onclick="wizardFinalizeV2()">Finalizar parecer</button></div>`)}
function wizardReport(){let entries=wizardEntries(),activityIds=[...new Set(entries.flatMap(item=>item.activityIds))],photos=entries.flatMap(item=>item.photos),photoNote=entries.map(item=>item.photoNote).filter(Boolean).join('\n\n'),finalText=typeof configuredFinalText==='function'?configuredFinalText():'';let found=data.reports.find(r=>String(r.studentId)===String(wizard.studentId)),payload={text:wizard.text,activityIds,photoNote,photos,entries,useFinalText:!!wizard.useFinalText,finalText:wizard.useFinalText?(wizard.finalText||finalText):''};if(found){Object.assign(found,payload);return found}let report={id:Date.now(),studentId:wizard.studentId,status:'draft',...payload};data.reports.unshift(report);return report}

function documentDraftHtml(){let main=(wizard.text||'').split(/\n{2,}/).filter(Boolean).map(part=>`<p>${esc(part)}</p>`).join('');let entries=wizardEntries().map(item=>{let note=item.photoNote?`<p>${esc(item.photoNote)}</p>`:'';let photos=item.photos?.length?`<div class="activity-photos">${item.photos.map(src=>`<img src="${src}" alt="Foto da vivência">`).join('')}</div>`:'';return `<section class="document-entry">${note}${photos}</section>`}).join('');return `${main}${entries}`}
function wizardReviewV2(){bufferStepTwo();let student=data.students.find(x=>x.id===wizard.studentId);wizardOpen(`<p class="wizard-step">ETAPA 3 DE 3 · REVISÃO</p><h2 class="modal-title">Rascunho do documento</h2><p class="modal-subtitle">Prévia formatada para o documento final.</p><div class="review-box"><strong>${esc(student.name)}</strong>${documentDraftHtml()}</div><div class="form-actions"><button class="secondary" type="button" onclick="wizardActivitiesV2()">Voltar</button><button class="secondary" type="button" onclick="wizardAddMore()">Adicionar mais</button><button class="secondary" type="button" onclick="saveWizardDraft()">Salvar rascunho</button><button class="primary" type="button" onclick="wizardFinalizeV3()">Finalizar parecer</button></div>`)}
function wizardFinalizeV3(){try{bufferStepTwo();let report=wizardReport();report.status='review';try{save()}catch(error){console.warn('Rascunho muito grande para o armazenamento local.',error);render()}let student=data.students.find(x=>x.id===report.studentId);wizardOpen(`<p class="wizard-step">PRÉVIA FINAL</p><h2 class="modal-title">Parecer pronto para entrega</h2><p class="modal-subtitle">Confira a versão que será entregue. Ela continua como rascunho até a confirmação.</p><div class="review-box"><strong>${esc(student.name)}</strong>${documentDraftHtml()}</div><div class="form-actions"><button class="secondary" type="button" onclick="wizardReviewV2()">Voltar para edição</button><button class="primary" type="button" onclick="deliverReport(${report.id})">Entregar parecer</button></div>`)}catch(error){console.error(error);alert('Não foi possível finalizar o parecer. Verifique os campos preenchidos e tente novamente.')}}

async function wizardFinalizeV3(){try{bufferStepTwo();let report=wizardReport(),student=data.students.find(x=>String(x.id)===String(report.studentId));let response=await fetch('api.php?resource=reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student:{name:student.name,birthDate:student.birthDate||'',classId:student.classId||1},text:report.text,activityIds:report.activityIds,entries:report.entries,imageEditorMode:wizard.imageEditorMode||'none'})});let result=await response.json();if(!response.ok)throw new Error(result.error||'Falha ao salvar no banco.');report.databaseId=result.id;report.status='review';save();wizardOpen(`<p class="wizard-step">PRÉVIA FINAL</p><h2 class="modal-title">Parecer pronto para entrega</h2><p class="modal-subtitle">Rascunho salvo no banco de dados. Confira antes de entregar.</p><div class="review-box">${configuredHeaderHtml()}${studentDocumentHeader(student)}${documentDraftHtml()}</div><div class="form-actions"><button class="secondary" type="button" onclick="wizardReviewV2()">Voltar para edição</button><button class="primary" type="button" onclick="deliverReport(${report.id})">Entregar parecer</button></div>`)}catch(error){console.error(error);alert(error.message)}}

function compactForStorage(value){return JSON.parse(JSON.stringify(value,(key,item)=>key==='photos'||key==='photo'?'':item))}
function save(){try{localStorage.setItem(KEY,JSON.stringify(compactForStorage(data)))}catch(error){console.warn('Não foi possível salvar a cópia local.',error)}render()}
function persistWizard(){try{localStorage.setItem(WIZARD_KEY,JSON.stringify(compactForStorage(wizard)))}catch(error){console.warn('Rascunho local sem imagens.',error)}}
try{localStorage.setItem(KEY,JSON.stringify(compactForStorage(data)))}catch(error){console.warn(error)}

async function loadReports(){try{let response=await fetch('api.php?resource=reports&summary=1');if(!response.ok)throw new Error();let reports=await response.json();reports=reports.map(r=>({...r,status:['done','concluido','concluído','entregue'].includes(String(r.status).toLowerCase())?'done':'draft'}));reports.forEach(r=>{let student=data.students.find(s=>String(s.id)===String(r.studentId));if(!student){student={id:r.studentId,name:r.name,birthDate:r.birthDate,classId:r.classId,avatar:r.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()};data.students.push(student)}});data.reports=reports;render()}catch(error){console.warn('Não foi possível carregar os pareceres.',error)}}
async function deliverReport(id){let report=data.reports.find(x=>x.id===id),databaseId=report?.databaseId||report?.id;if(!databaseId)return alert('Este parecer ainda não foi salvo no banco de dados.');try{let response=await fetch('api.php?resource=reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deliverId:databaseId})});let result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Falha ao entregar.');report.status='done';report.deliveredAt=new Date().toISOString();clearWizard();wizardClose();save();downloadReport(report.id);setTimeout(()=>downloadPdf(report.id),400);setTimeout(()=>loadReports(),1200)}catch(error){console.error(error);alert(error.message||'Não foi possível concluir o parecer no banco de dados.')}}
async function saveInitialDraft(){bufferStepOne();let student=data.students.find(s=>String(s.id)===String(wizard.studentId));if(!student)return;try{let response=await fetch('api.php?resource=reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({draft:true,student:{name:student.name,birthDate:student.birthDate||'',classId:student.classId||1},text:wizard.text||'',activityIds:[],entries:[],useFinalText:!!wizard.useFinalText,finalText:wizard.useFinalText?(wizard.finalText||''):'',imageEditorMode:wizard.imageEditorMode||'none'})});let result=await response.json();if(!response.ok)throw new Error(result.error||'Erro ao salvar.');wizard.databaseId=result.id;persistWizard();alert('Rascunho salvo com sucesso.')}catch(error){alert(error.message)}}
async function saveDraftEverywhere(){try{if($('#wizardText'))bufferStepOne();if($('#wizardPhotoNote'))bufferStepTwo();let student=data.students.find(s=>String(s.id)===String(wizard.studentId));if(!student)throw new Error('Selecione um aluno antes de salvar.');let entries=wizardEntries(),activityIds=[...new Set(entries.flatMap(entry=>entry.activityIds||[]))],finalText=typeof configuredFinalText==='function'?configuredFinalText():'';let response=await fetch('api.php?resource=reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({draft:true,student:{name:student.name,birthDate:student.birthDate||'',classId:student.classId||1},text:wizard.text||'',activityIds,entries,useFinalText:!!wizard.useFinalText,finalText:wizard.useFinalText?(wizard.finalText||finalText):'',imageEditorMode:wizard.imageEditorMode||'none'})});let result=await response.json();if(!response.ok)throw new Error(result.error||'Erro ao salvar o rascunho.');let report=data.reports.find(r=>String(r.studentId)===String(wizard.studentId));if(!report){report={id:Date.now(),studentId:wizard.studentId,status:'draft'};data.reports.unshift(report)}Object.assign(report,{databaseId:result.id,text:wizard.text||'',activityIds,entries,useFinalText:!!wizard.useFinalText,finalText:wizard.useFinalText?(wizard.finalText||finalText):'',photoNote:entries.map(e=>e.photoNote).filter(Boolean).join('\n\n')});persistWizard();save();alert('Rascunho salvo com sucesso no banco de dados.')}catch(error){console.error(error);alert(error.message)}}
async function saveWizardDraft(){await saveDraftEverywhere()}
loadReports();
window.addEventListener('focus',loadReports);

function studentFormV5(){let options=data.classes.map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.shift)}</option>`).join('');open(`<h2 class="modal-title">Novo aluno</h2><p class="modal-subtitle">Inclua os dados e uma foto para identificação no parecer.</p><div class="form-grid"><div class="field"><label>Nome completo</label><input id="name" required autofocus></div><div class="field"><label>Data de nascimento</label><input id="birthDate" type="date" required></div><div class="field"><label>Turma</label><select id="studentClass" required>${options}</select></div><div class="field"><label>Foto do aluno</label><input id="studentPhoto" type="file" accept="image/*"></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="addStudentSaveV5()">Salvar aluno</button></div>`)}
async function addStudentSaveV5(){let name=$('#name').value.trim(),birthDate=$('#birthDate').value,file=$('#studentPhoto').files[0];if(!name)return $('#name').focus();if(!birthDate)return $('#birthDate').focus();let photo=file?await fileAsDataUrl(file):'';try{let response=await fetch('api.php?resource=children',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,birthDate,classId:+$('#studentClass').value,photo})});let result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível salvar o aluno.');close();await loadChildren()}catch(error){alert(error.message)}}
function studentDocumentHeader(student){let className=student.className||data.classes.find(c=>c.id===student.classId)?.name||'Turma não informada',birth=student.birthDate?student.birthDate.split('-').reverse().join('/'):'Não informado';return `<div class="document-student"><div><p><b>NOME:</b> ${esc(student.name)}</p><p><b>D.N.:</b> ${esc(birth)}</p><p><b>TURMA:</b> ${esc(className)} <span style="margin-left:90px"><b>ANO:</b>${new Date().getFullYear()}</span></p></div>${student.photo?`<img src="${student.photo}" alt="Foto do aluno">`:''}</div>`}
function configuredHeaderHtml(){let header=JSON.parse(localStorage.getItem(HEADER_KEY)||'{}'),text=[header.network,header.school,header.contact].filter(Boolean).join('\n');return text||header.logo?`<div class="document-header"><div>${esc(text)}</div>${header.logo?`<img src="${header.logo}" alt="Logo institucional">`:''}</div>`:''}
function wizardReviewV2(){bufferStepTwo();importSelectedRegisteredActivities();persistWizard();let student=data.students.find(x=>String(x.id)===String(wizard.studentId));if(!student)return alert('Não foi possível localizar o aluno deste parecer.');wizardOpen(`<p class="wizard-step">ETAPA 3 DE 3 · REVISÃO</p><h2 class="modal-title">Rascunho do documento</h2><p class="modal-subtitle">Prévia formatada para o documento final.</p><div class="review-box">${configuredHeaderHtml()}${studentDocumentHeader(student)}${documentDraftHtml()}</div><div class="form-actions"><button class="secondary" type="button" onclick="wizardActivitiesV2()">Voltar</button><button class="secondary" type="button" onclick="wizardAddMore()">Adicionar mais</button><button class="secondary" type="button" onclick="saveWizardDraft()">Salvar rascunho</button><button class="primary" type="button" onclick="wizardFinalizeV3()">Finalizar parecer</button></div>`)}
$('#addStudent').onclick=studentFormV5;

function editStudent(id){let student=data.students.find(s=>String(s.id)===String(id));if(!student)return;let options=data.classes.map(c=>`<option value="${c.id}" ${String(c.id)===String(student.classId)?'selected':''}>${esc(c.name)} · ${esc(c.shift)}</option>`).join('');open(`<h2 class="modal-title">Editar aluno</h2><p class="modal-subtitle">Atualize os dados cadastrais e a foto de identificação.</p><div class="form-grid"><div class="field"><label>Nome completo</label><input id="editStudentName" value="${esc(student.name)}" required></div><div class="field"><label>Data de nascimento</label><input id="editStudentBirth" type="date" value="${esc(student.birthDate||'')}"></div><div class="field"><label>Turma</label><select id="editStudentClass">${options}</select></div><div class="field"><label>Nova foto <span class="muted">(opcional)</span></label><input id="editStudentPhoto" type="file" accept="image/*"></div></div><div class="form-actions"><button class="secondary" type="button" onclick="document.querySelector('#modal').close()">Cancelar</button><button class="primary" type="button" onclick="saveStudentEdit('${String(student.id)}')">Salvar alterações</button></div>`)}
async function saveStudentEdit(id){let student=data.students.find(s=>String(s.id)===String(id));if(!student)return;let name=$('#editStudentName').value.trim(),file=$('#editStudentPhoto').files[0];if(!name)return $('#editStudentName').focus();student.name=name;student.birthDate=$('#editStudentBirth').value;student.classId=+$('#editStudentClass').value;student.avatar=name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();if(file)student.photo=await fileAsDataUrl(file);close();save()}
async function saveStudentEdit(id){let student=data.students.find(s=>String(s.id)===String(id));if(!student)return;let name=$('#editStudentName').value.trim(),file=$('#editStudentPhoto').files[0];if(!name)return $('#editStudentName').focus();if(file)student.photo=await fileAsDataUrl(file);let response=await fetch('api.php?resource=children',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({databaseId:student.databaseId||String(student.id).replace('db-',''),name,birthDate:$('#editStudentBirth').value,classId:+$('#editStudentClass').value,photo:student.photo||''})});let result=await response.json();if(!response.ok)return alert(result.error||'Não foi possível salvar o aluno.');Object.assign(student,{id:'db-'+result.id,databaseId:result.id,name,birthDate:$('#editStudentBirth').value,classId:+$('#editStudentClass').value,avatar:name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()});close();save()}
async function loadChildren(){try{let response=await fetch('api.php?resource=children');if(!response.ok)return;let children=await response.json();data.students=children.map(child=>({...child,avatar:child.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}));render()}catch(error){console.warn(error)}}
loadChildren();

async function loadHeaderSettings(){let settings=JSON.parse(localStorage.getItem(HEADER_KEY)||'{}');try{let response=await fetch('api.php?resource=header-settings');if(response.ok){settings=await response.json();localStorage.setItem(HEADER_KEY,JSON.stringify(settings))}}catch(error){console.warn('Nao foi possivel carregar o cabecalho do usuario.',error)}$('#headerNetwork').value=settings.network||'';$('#headerSchool').value=settings.school||'';$('#headerContact').value=settings.contact||'';$('#headerLogoPreview').innerHTML=settings.logo?`<img src="${settings.logo}" alt="Logo">`:''}
$('#saveHeaderSettings').onclick=async()=>{let logoFile=$('#headerLogo').files[0],old=JSON.parse(localStorage.getItem(HEADER_KEY)||'{}'),logo=old.logo||'';if(logoFile)logo=await fileAsDataUrl(logoFile);let settings={network:$('#headerNetwork').value.trim(),school:$('#headerSchool').value.trim(),contact:$('#headerContact').value.trim(),logo};let response=await fetch('api.php?resource=header-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});let result=await response.json().catch(()=>({}));if(!response.ok)return alert(result.error||'Nao foi possivel salvar o cabecalho.');localStorage.setItem(HEADER_KEY,JSON.stringify(settings));loadHeaderSettings();alert('Cabeçalho salvo com sucesso.')};
loadHeaderSettings();

function editReport(id){let report=data.reports.find(r=>String(r.id)===String(id));if(!report)return;let draft={studentId:report.studentId,text:report.text||'',activityIds:[],photoNote:'',photos:[],entries:report.entries||[{activityIds:report.activityIds||[],photoNote:report.photoNote||'',photos:report.photos||[]}]};wizard=draft;let student=data.students.find(s=>String(s.id)===String(report.studentId));if(report.status==='done'){wizardOpen(`<p class="wizard-step">PARECER ENTREGUE</p><h2 class="modal-title">Revisão do parecer</h2><p class="modal-subtitle">Visualização completa do documento entregue.</p><div class="review-box">${configuredHeaderHtml()}${studentDocumentHeader(student)}${documentDraftHtml()}</div><div class="form-actions"><button class="secondary" type="button" onclick="wizardClose()">Fechar</button><button class="secondary" type="button" onclick="reopenReport(${report.id})">Reabrir parecer</button><button class="secondary" type="button" onclick="downloadPdf(${report.id})">Baixar PDF</button><button class="primary" type="button" onclick="downloadReport(${report.id})">Baixar DOCX</button></div>`);return}persistWizard();wizardStart(false,draft)}
async function reopenReport(id){let report=data.reports.find(r=>String(r.id)===String(id));try{let response=await fetch('api.php?resource=reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reopenId:report.databaseId||report.id})});let result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Não foi possível reabrir o parecer.');await loadReports();wizardClose();editReport(id)}catch(error){alert(error.message)}}
